#!/bin/python3


#


def distinct_powers(base_range, power_range):
    """Finds all the distinct terms generated by a^b"""
    num_seq = set()
    base_min, base_max = base_range
    power_min, power_max = power_range
    for a in range(base_min, base_max+1):
        for b in range(power_min, power_max+1):
            num = pow(a, b)
            num_seq.add(num)
    return len(num_seq)


if __name__ == "__main__":
    test = [ \
            [(2, 100), (2, 100)],
            [(2, 5), (2, 5)]]
    params = test[0]
    ans = distinct_powers(*params)
    print(ans)
